// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:48659776994:web:4bbf1ff25ec6424adc25bb',
    messagingSenderId: '48659776994',
    projectId: 'quicklink-cd078',
    authDomain: 'quicklink-cd078.firebaseapp.com',
    storageBucket: 'quicklink-cd078.firebasestorage.app',
    measurementId: 'G-Y5MR5B49M0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:48659776994:android:b6cfc937eed4dc7cdc25bb',
    messagingSenderId: '48659776994',
    projectId: 'quicklink-cd078',
    storageBucket: 'quicklink-cd078.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:48659776994:ios:dd783fc52ab7a63edc25bb',
    messagingSenderId: '48659776994',
    projectId: 'quicklink-cd078',
    storageBucket: 'quicklink-cd078.firebasestorage.app',
    iosBundleId: 'com.example.quickLink',
  );

}
